os:
- osx
language:
- c
env:
  global:
  - NODE_VERSION=5
  - secure: atVLiBasdkLKKp4KohO8kDlNqZooZ+oQkmirga+GxTxPt+X8PS/3cuGREnyCXYwV5FFll8me9INhNXMR6gq/OvKKKNIM3Ib307UrxNAIGVF+0YavFS6bIFWyUF3ib0ZThkw4tpLwwvNdrZqy49eSuMxwF+QghIgjNvS40HR6Jpa9LurAWSRqP7k4xggyxsDLGDHlc+ywJSMjAccj7IsaYW17y4FT6Znpgk7hfxqezRi+LLsBOg1g8M9sIqdfJEKTRfrOcHB296EVdXnQd0o/uBPJ096BOZuPgDRuSteBncdbtQOD1w8IKZDtCheT1ijQm/w0pvd1hEGeC6WSVbaRGUkLcqSCTKXeHTE+nFgCnAjCOQnQLXMLxg3VC906E6vK+hs5g4Laq/WePonYQCKswIKzC/+jedtAvJ/kwHvAdOE/982lF1MRDA4p9Yne5wFyK5u5Pf7FvqZSq97i0J5vrsqC1oNkLWJbRW8KPzUsd7DDYbaFTZRS/t2Hl3kj5aeQk+WsJXzNOw7xd2HBa9WHDwSfZOOGw92gSU08MHM3MB2wO7iU7oVDGBnQbI2+el3ifO7C8N1kUBpoJcUMj6XyNy6L1xePdZxHDkVnHc0HfNc0xLC3zSz7b713lrtr5CuN9c711eg8fumXyY6kEbqfTNdhSoDOlqFtbHiaj6gDpRw=
  - secure: KDFCcMotQHgdvFsHnz2+TQpW3qYygHveaUyBoe4nukZ3PLh6stqitkYSDMJ07YWf2dbNm1yy8HdBeCyh5zBxSOrmqemY/yL+FUlhPwyMYl4YwKvTRTvVVA82qiD9YY9F0TlcRIeBU8C/PVo3Uym7wz9c+ewoF70esCl2EEqZBUMSEuBHJo4iF1R7EQKr5s+LOdUtcYATu2hQRg6qpSIElSp5AzrMTXI5yWbFDeHxF7QI2LED0uCnm3/sg5dakjPERksWH+IUOU9EIm22qeiMHQUUnh6Whuu4aD2jpdd55iVY5mkmo3HfWRrPNlq/N1UoVyH+XcgMZyE4bQWUv8vZ52+99Xrz8PagxNvNH1RJqNaULw5XE0H+g1xaMmH/8KWuGLtDUolUSIEhDaynf8Uk1EzBQgA76BJlBAY2yXBoPQ/BXSrXLXcbgwj2/8DHlBduPy8AfPhgnmyav0vNK7LXi8VYfpvsBdLPLYzSi8F/WihWJ29BCBHT2cAoK5ck9I0FmFmHtkRCogt+0sLf9+NsQcafp/vS2GrFwR51EZc/Ms9cV+e9inuaElAVJ0HZvTyrb7Noufxp3YhLbMnFJ/v5slZBxFZek7gxsM8O5PZtH4ZNUUUc5pxNHWjQm/Vtv1APVDKtSS+NVaVsLCHjyCTjKrXDf6l7/36cEjFZeNMrBPw=
cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.npm
before_install:
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use --delete-prefix $NODE_VERSION
install:
- npm prune
- npm install
script:
- npm run build