osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
- yarn

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release -- -wl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"