osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - clang-3.8

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" && sudo apt-get update && sudo apt-get install clang-3.8; fi

install:
- nvm install 6
- npm install electron-builder@next # force install next version to test electron-builder
- npm install
#- npm install https://github.com/develar/__test-app-releases/releases/download/v1.0.4/electron-builder-0.0.0-semantic-release.tgz # force install next version to test electron-builder
- npm prune

script:
- npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"